<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LP-PC0MQFYK" name="Com.crm.qa.TestCases.SignUpPageTest" tests="15" failures="1" timestamp="13 Aug 2018 15:40:54 GMT" time="24.969" errors="0">
  <testcase name="SignUpbutton" time="21.516" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpGetTitleTest" time="0.013" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpEditionDropdownValuesTest" time="0.097" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyAllFieldsAreRequiredLabelTest" time="0.035" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyTermsAndConditionsLinkTest" time="0.031" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyDisabledIAgreeCheckboxTest" time="0.043" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyDisabledSubmitbuttonTest" time="0.026" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpEditionDropdownTest" time="0.120" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpFormTest" time="1.329" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyEnabledIAgreeCheckboxTest" time="0.021" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="ClickingOnCheckboxTest" time="0.065" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyEnabledSubmitbuttonTest" time="0.023" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SubmitbuttonTest" time="0.585" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyAlert" time="0.019" classname="Com.crm.qa.TestCases.SignUpPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Alert Msg Is Getting Displayed Wrong expected [Errors were encountered: This username is already in use by another user. Please select a different username.] but found [Errors were encountered: 

This username is already in use by another user. Please select a different username.
]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Alert Msg Is Getting Displayed Wrong expected [Errors were encountered: This username is already in use by another user. Please select a different username.] but found [Errors were encountered: 

This username is already in use by another user. Please select a different username.
]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Com.crm.qa.TestCases.SignUpPageTest.VerifyAlert(SignUpPageTest.java:147)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyAlert -->
  <testcase name="backToLoginPage" time="1.046" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
</testsuite> <!-- Com.crm.qa.TestCases.SignUpPageTest -->
